---
  version: '3'

  services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      image: yulia633/xsolla-test
      volumes:
        - .:/app
      command: ["make", "lint"]
